"""Add timestamp fields to models

Revision ID: 7e29d8746a69
Revises: 
Create Date: 2024-12-26 11:05:37.866862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e29d8746a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_release', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('time_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('time_series_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_series_type', schema=None) as batch_op:
        batch_op.drop_column('date_update')
        batch_op.drop_column('date_create')
        batch_op.drop_column('description')

    with op.batch_alter_table('time_series', schema=None) as batch_op:
        batch_op.drop_column('date_update')
        batch_op.drop_column('date_create')

    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('date_update')
        batch_op.drop_column('date_create')
        batch_op.drop_column('date_release')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('date_update')
        batch_op.drop_column('date_create')

    # ### end Alembic commands ###
